version: "3.7"

services:
  web:
    build: 
      context: .
      args:
        CONTRAST_INSTALL: Assess # Node has two agents - replace 'ASSESS' with 'PROTECT' or 'OF' as needed
    command:  sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && npm run db:seed && npm run contrast; do sleep 2; done"
    ports:
      - "4000:4000"
    volumes:
      - ./contrast_security.yaml:/home/node/app/contrast_security.yaml
      - ./logs:/home/node/app/logs
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/nodegoat
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"