version: "3.7"

services:
  web:
    build: .
    command: npm run test-with-contrast
    ports:
      - "4000:4000"
    volumes:
      - ./contrast_security.yaml:/home/node/app/contrast_security.yaml
      - ./logs:/home/node/app/logs
    environment:   
      - MONGODB_URI=mongodb://mongo:27017/nodegoat
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
